### ISSUE TITLE
Charge storage during the night

### ISSUE THREAD

**Issue by ejay** [B00ms/energyGridSimulation#32] opened 2016-06-03 09:28 UTC
During night h ε [22, 4] charge storage up to 50% of cMax

**Comment by B00ms** [comment] 2016-06-07 08:15
Resolved in https://github.com/B00ms/energyGridSimulation/commit/9ba1f19847af331fdcc7152fb34ba0881e707d55 and https://github.com/B00ms/energyGridSimulation/commit/11aeda50101ec7728b045d7ae69391d86c1da472

**Comment by B00ms** [comment] 2016-06-07 08:15
Please double check that it works as intended :P.

**Closed as completed** 2016-06-09 15:30 UTC
